name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4        # clone repo
      - uses: actions/setup-python@v5    # install Python
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: pytest tests/
      - run: pytest tests/
        env:
            LANGFUSE_PUBLIC_KEY: ${{ secrets.LANGFUSE_PUBLIC_KEY }}
            LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}

